version: '3.8'

services:
  register-service:
    image: service
    build:
      context: .
      dockerfile: Service/Dockerfile
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: FreeVoteDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: